# vix 지수 데이터 전처리

In [11]:
import pandas as pd

In [12]:
vix = pd.read_csv("/content/vix.csv", header=None)
vix

                                                      0
0     2022년 05월 23일\t19.44\t19.60\t19.84\t19.24\t-\t...
1     2022년 05월 20일\t19.10\t19.45\t19.52\t18.92\t-\t...
2     2022년 05월 19일\t20.42\t20.21\t20.44\t20.01\t-\t...
3     2022년 05월 18일\t18.40\t18.24\t18.74\t18.20\t-\t...
4     2022년 05월 17일\t19.06\t19.73\t19.73\t19.02\t-\t...
...                                                 ...
2156  2013년 08월 12일\t14.72\t14.84\t15.22\t14.64\t-\t...
2157  2013년 08월 09일\t14.38\t14.95\t15.05\t14.38\t-\t...
2158  2013년 08월 08일\t14.96\t14.84\t15.42\t14.77\t-\t...
2159  2013년 08월 07일\t15.35\t15.02\t15.42\t14.80\t-\t...
2160  2013년 08월 06일\t14.98\t14.79\t14.98\t14.61\t-\t...

[2161 rows x 1 columns]

In [13]:
vix['date'] = 0
vix['vix'] = 0

for i in range(len(vix)):
    vix['date'][i] = vix.iloc[i,0].split("\t")[0]
    vix['vix'][i] = float(vix.iloc[i,0].split("\t")[1])

vix=vix[["date","vix"]]
vix['date'] = vix['date'].apply(lambda x:x.split("년 ")[0])+vix['date'].apply(lambda x:x.split("년 ")[1].split("월 ")[0])+vix['date'].apply(lambda x:x.split("년 ")[1].split("월 ")[1].replace("일",""))
vix['date']=pd.to_datetime(vix['date'])

vix

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

           date  vix
0    2022-05-23   19
1    2022-05-20   19
2    2022-05-19   20
3    2022-05-18   18
4    2022-05-17   19
...         ...  ...
2156 2013-08-12   14
2157 2013-08-09   14
2158 2013-08-08   14
2159 2013-08-07   15
2160 2013-08-06   14

[2161 rows x 2 columns]

In [14]:
vix.to_csv("vix_refined.csv")

#  news_title_days 전처리

In [15]:
days = pd.read_csv("/content/news_title_days.csv")
days = days.drop(['Unnamed: 0'], axis=1)
days

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2006-1-1,2006 상승테마 종목 관심집중,[증권 기상도] 2분기 짧은 휴식‥ 하반기는 쾌청,NaN,[주간증시전망]‘1월효과’재현될지 관심 집중,NaN,[1월2일의 투자전략]금융·소비株 강세 전망,NaN,[2006재테크 전략]“브랜드가 주가파워”1등기업 주주 돼라,[2006재테크 전략]저PER·저PBR株로 2006 고수익 낚아라,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-1-2,NaN,(마켓서핑)새술은 새부대에,[1월3일의 투자전략]기관 매수세 상승 동력으로 작용할것,[내일의 전략]연초 '삼순이 전략'으로,(여의도시각)초심,[코스피마감]PR 매물에도 1390 근접,악재공시 확인하고 투자하라,[시황]외국인 컴백…시가총액 상위주 강세,“올 최대테마株 는 와이브로”,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-1-3,[내일의 전략]대형주로 갈아타라더니?,[1월4일의 투자전략]“조정이용 IT·車 우량주 매수 기회로”,NaN,"(마켓서핑)환율, 걱정되네!",(여의도시각)기회비용,환율 하락…‘1월 효과’ 최대 복병,[코스피마감]PR매물 딛고 반등..'1390 첫돌파',[코스닥마감]상승세 지속..바이오도 가세,주가 보합권 혼조세…개인 ‘사자’,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006-1-4,NaN,(마켓서핑)`BUY 코리아`,[내일의 전략]계속 오를 수 있을까?,[1월5일의 투자전략]“1월 외국인 순매수 전환 기대할만”,(여의도시각)반컵의 물,손해율 급상승 보험株에 폭설?,무선인터넷 '2차수혜株'는 어떤 종목,(테마돋보기)게임株에 무슨 일이?,[1400시대]펀드매니저 어떤 종목 사나,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-1-5,[1월6일의 투자전략]“환율 하락 저가매수 기회로 삼아야”,[내일의 전략]너무 낙관적인거 아냐,NaN,(마켓서핑)문제는 속도다,(여의도시각)유연함을 발휘할 때,중소형 금융株 주목할만,이젠 나노테마로 눈돌려볼까,[코스닥마감] 투자심리 위축...740선 실패,[코스피마감]5일만의 조정..막판 낙폭만회,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6319,2022-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6320,2022-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6321,2022-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6322,2022-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6323,2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:

# datetime으로 바꾸기

#format int형 정수 앞에 0채우기
days['0']=days['0'].apply(lambda x:(x.split('-')[0]))+days['0'].apply(lambda x:format(int(x.split('-')[1]),'02'))+days['0'].apply(lambda x:format(int(x.split('-')[2]),'02'))
drop_lst = []

for i in range(2006,2023):
    for j in ["02","04","06","09","11"]:
        drop_lst.append(f"{str(i)}{j}31")
    for s in ["29","30"]:
        drop_lst.append(f"{i}02{s}")


a = list(days['0'])
for i in drop_lst:
    a.remove(i)

days['0'] = pd.Series(a)

days['0']=pd.to_datetime(days['0'])

# 컬럼명 정리
columns_lst = ["date"]
columns_lst+=list(range(1,40))
columns_lst

days.columns = columns_lst
days

,date,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2006-01-01,2006 상승테마 종목 관심집중,[증권 기상도] 2분기 짧은 휴식‥ 하반기는 쾌청,NaN,[주간증시전망]‘1월효과’재현될지 관심 집중,NaN,[1월2일의 투자전략]금융·소비株 강세 전망,NaN,[2006재테크 전략]“브랜드가 주가파워”1등기업 주주 돼라,[2006재테크 전략]저PER·저PBR株로 2006 고수익 낚아라,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2006-01-02,NaN,(마켓서핑)새술은 새부대에,[1월3일의 투자전략]기관 매수세 상승 동력으로 작용할것,[내일의 전략]연초 '삼순이 전략'으로,(여의도시각)초심,[코스피마감]PR 매물에도 1390 근접,악재공시 확인하고 투자하라,[시황]외국인 컴백…시가총액 상위주 강세,“올 최대테마株 는 와이브로”,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2006-01-03,[내일의 전략]대형주로 갈아타라더니?,[1월4일의 투자전략]“조정이용 IT·車 우량주 매수 기회로”,NaN,"(마켓서핑)환율, 걱정되네!",(여의도시각)기회비용,환율 하락…‘1월 효과’ 최대 복병,[코스피마감]PR매물 딛고 반등..'1390 첫돌파',[코스닥마감]상승세 지속..바이오도 가세,주가 보합권 혼조세…개인 ‘사자’,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2006-01-04,NaN,(마켓서핑)`BUY 코리아`,[내일의 전략]계속 오를 수 있을까?,[1월5일의 투자전략]“1월 외국인 순매수 전환 기대할만”,(여의도시각)반컵의 물,손해율 급상승 보험株에 폭설?,무선인터넷 '2차수혜株'는 어떤 종목,(테마돋보기)게임株에 무슨 일이?,[1400시대]펀드매니저 어떤 종목 사나,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2006-01-05,[1월6일의 투자전략]“환율 하락 저가매수 기회로 삼아야”,[내일의 전략]너무 낙관적인거 아냐,NaN,(마켓서핑)문제는 속도다,(여의도시각)유연함을 발휘할 때,중소형 금융株 주목할만,이젠 나노테마로 눈돌려볼까,[코스닥마감] 투자심리 위축...740선 실패,[코스피마감]5일만의 조정..막판 낙폭만회,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6319,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6320,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6321,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6322,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6323,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# vix지수가 있는 날짜에 해당하는 기사만
days = days[days["date"].isin(set(vix["date"]))]

In [18]:
days.to_csv("days.csv")

In [21]:
days.reset_index(drop=True, inplace=True)

In [22]:
days

,date,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2013-08-06,"코스피, 기관 '사자'에 나흘만에 상승…삼성전자 '반등'","[내일의전략] 더위에 지친 카지노株, GO or STOP?",NaN,'변동성' 커지자 내수주 다시 고개,NaN,삼성전자를 바라보는 두가지 시각,(뉴욕전망대)우리 동네는 내가 지킨다,(亞증시 오후)대부분 상승..전날 폭락 만회,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-08-07,<증시전망> 출구전략 우려 완화로 반등 전망,[뉴욕마감]지표 부진·성장 전망 하향에 하락,[유럽마감]연준 QE 지속 기대감에 상승,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-08-08,NaN,[증시 전망대] 美 Fed 양적완화 축소 움직임,1Q 실적따라 드라마 제작사株 희비 갈려,코스피 무너져도 外人 바구니엔 □□□ 담겼다,NaN,"[주간뉴욕전망] 버냉키, 양적완화 불확실성 줄이나",[주간전망대]공공기관 평가 발표..CEO 교체 본격화,NaN,실적 개선株 주목..IT '러브콜 1순위',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-08-09,0.3% 하락…FOMC 앞두고 '관망 모드',NaN,매수 머뭇거리는 연기금,NaN,돈줄 꽉 막힌 해운株 험난한 뱃길,고배당·보험·통신·홈쇼핑…예측불허 훅과 잽 버틸 '맷집株',NaN,이 와중에…실적 마저 안도와주네,(亞증시 오후)연준 감축 우려 완화..日 증시 상승,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-08-12,G2 리스크에 코스피 2% 급락…10개월래 최저,NaN,"공포지수 치솟은 증시, 투자전략은?",NaN,[美 출구전략 국내 금융시장 패닉] 작년 9월 美 3차 양적완화 이후 주가 상승분 ...,"전문가들 ""美출구전략 대비 실질적 대응 필요하다""",달러 강세 맞춰 투자 전략 다시 짜라,불량 우선주 퇴출 제도…주가 조작 줄어들까,버냉키 쇼크에 하락..亞증시 '2년만에 최저',...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2155,2022-05-17,NaN,[마켓뷰] 외인·기관 패닉셀 시작됐나... 시총 상위 100개 종목중 98개 파란불,[Asia마감] 악재만 크게 보이네…일제히 급락,NaN,"[시황종합] ""악재 또 악재"" 코스피 2.56% 하락…코스닥 900선 붕괴",NaN,[코스닥 마감] 1년2개월만에 880선까지 떨어져…2% 이상 하락,NaN,[외환마감]환율 1200원 눈앞…FOMC 경계·지정학 위험 `달러 강세`,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2156,2022-05-18,[유럽개장]장초반 상승세…英 FTSE 1.22%↑,NaN,"[마켓뷰] 코스피, 결국 반등 실패…4거래일 연속 밀렸다",[Asia마감] 닛케이 한때 2만7000선 붕괴…中증시는 ↑,NaN,"[마감시황]코스피, FOMC 경계감에 0.4%↓…4일째 하락",NaN,[시황종합] 코스피 4일째 하락에 2700선도 위태…FOMC 경계감,NaN,...,NaN,[유럽증시] 미 FOMC 정례회의 주목하며 소폭 상승,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2157,2022-05-19,[유럽개장] 일제히 하락 개장…英 1.14%↓,"[Asia마감]""美 3월 금리인상"" 예상된 발언에도 일제히 와르르",NaN,[마감시황]패닉장...코스피 2600선·코스닥 800선 '풍전등화',NaN,[외환마감]`매 발톱` 드러낸 파월…환율 `1년반 최고` 1200원대,NaN,[시황종합] 3.5% 빠진 코스피 2500선 코앞…外人 1.6조 '팔자',NaN,...,NaN,[유럽증시] 미 FOMC 정례회의 주시하며 일제히 상승,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2158,2022-05-20,[유럽개장] 장초반 약세…獨 0.88%↓,"[Asia마감]""많이 빠졌네""…日 반발 매수세에 2.09% 상승",NaN,"[마켓뷰] 롤러코스터 탄 코스피, 2600선 밑에서 급반등…외국인은 오늘도 ‘팔자’",NaN,"[마감시황]코스피, 반발매수 유입에 1.8% 상승",NaN,[시황종합] 코스피 6일만에 상승 2660선…SK하이닉스 6% ↑,NaN,...,[유럽증시] 미 GDP 개선 속 상승,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2159,2022-05-23,"[Asia마감] ""실적 기대 높은 주식 사자""…日 1%대 상승",NaN,반등 타이밍 온다?…서학개미 '이것' 모르면 또 물린다[월가시각],NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN